# -*- coding: utf-8 -*-
"""Multiple Linear Regression .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vX6ExQfTfHcuaVQYjULOZN_zrcFkJmHT
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

dataset = pd.read_csv('advertising.csv')
dataset

x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)

regressor = LinearRegression()
regressor.fit(x_train, y_train)

y_pred = regressor.predict(x_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test), 1)), 1))

y_pred_reshape = y_pred.reshape(len(y_pred), 1)
y_test_reshape = y_test.reshape(len(y_test), 1)


plt.figure(figsize=(10, 5))


plt.plot(y_pred_reshape, label='Predicted Sales', marker='o', linestyle='--')
plt.plot(y_test_reshape, label='Actual Sales', marker='x', linestyle='-')


plt.xlabel('Sample')
plt.ylabel('Sales')


plt.grid(True)
plt.legend()
plt.show()

regressor.score(x, y) * 100